### ISSUE TITLE
Unable to rake db:seed

### ISSUE THREAD

**Issue by olivermag** [olivermag/Bloccit#3]
``` Oliviers-MBP:Bloccit olivermag$ rake db:seed ```
``` rake aborted! ``` 
``` ActiveModel::MissingAttributeError: can't write unknown attribute `post_id' ```

**Comment by olivermag** [comment]
Rake db:reset causes the same bug

**Comment by fuzzyalej** [comment]
@olivermag you should mention or assign me to these issues so I get notified :)
